<?php

// Development fixture only; not approved NOSEE event information.
return [
    'slug' => 'environmental-data-training',
    'title' => 'Environmental Data Stewardship Training',
    'type' => 'training',
    'summary' => 'A development training programme covering metadata, version control, quality checks, and responsible data reuse.',
    'featured' => false,
    'image' => null,
    'image_alt' => null,
    'timezone' => 'Africa/Lagos',
    'start_date' => '2027-07-19',
    'end_date' => '2027-07-23',
    'schedule' => [
        'mode' => 'multi_day',
        'start_time' => null,
        'end_time' => null,
        'itinerary' => [
            [
                'date' => '2027-07-19',
                'start_time' => '09:00',
                'end_time' => '15:00',
                'title' => 'Data stewardship foundations',
                'description' => null,
            ],
            [
                'date' => '2027-07-20',
                'start_time' => '09:00',
                'end_time' => '15:00',
                'title' => 'Metadata practice',
                'description' => null,
            ],
            [
                'date' => '2027-07-21',
                'start_time' => '09:00',
                'end_time' => '15:00',
                'title' => 'Versioned workflows',
                'description' => null,
            ],
            [
                'date' => '2027-07-22',
                'start_time' => '09:00',
                'end_time' => '15:00',
                'title' => 'Quality checks',
                'description' => null,
            ],
            [
                'date' => '2027-07-23',
                'start_time' => '09:00',
                'end_time' => '13:00',
                'title' => 'Responsible reuse',
                'description' => null,
            ],
        ],
    ],
    'location' => [
        'type' => 'physical',
        'venue' => 'Development Training Centre',
        'address' => null,
        'city' => 'Port Harcourt',
        'country' => 'Nigeria',
        'platform' => null,
    ],
    'application_deadline' => null,
    'meeting_site_url' => null,
    'organiser' => 'NOSEE Development Training Team',
    'speakers' => [],
    'registration_url' => null,
    'body' => 'This fictional five-day training record provides development detail content for practical environmental data stewardship sessions.',
    'resources' => [],
];
